#!/usr/bin/env bash
# setup.sh — Seed test data and generate fixtures for ReplyIQ load tests.
#
# Run this once against your staging environment before executing k6 tests:
#   bash load-tests/setup.sh
#
# Prerequisites:
#   - STAGING_API_URL exported (e.g. https://api-staging.replyiq.com/api/v1)
#   - STAGING_EMAIL + STAGING_PASSWORD for an existing account
#   - curl, jq installed

set -euo pipefail

API="${STAGING_API_URL:-http://localhost:8000/api/v1}"
EMAIL="${STAGING_EMAIL:-loadtest@example.com}"
PASSWORD="${STAGING_PASSWORD:-LoadTestPass123!}"

echo "==> Target: $API"
echo ""

# ── 1. Authenticate ──────────────────────────────────────────────────────────
echo "==> Authenticating as $EMAIL"

LOGIN=$(curl -sf -X POST "$API/auth/login" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}")

TOKEN=$(echo "$LOGIN" | jq -r '.data.token')
if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
  echo "ERROR: Login failed. Check STAGING_EMAIL / STAGING_PASSWORD."
  exit 1
fi
echo "Token: ${TOKEN:0:20}..."

# ── 2. Get or create a chatbot ───────────────────────────────────────────────
echo "==> Fetching chatbots"

CHATBOTS=$(curl -sf "$API/chatbots" \
  -H "Authorization: Bearer $TOKEN")

CHATBOT_ID=$(echo "$CHATBOTS" | jq -r '.data[0].id // empty')
CHATBOT_PUBLIC_ID=$(echo "$CHATBOTS" | jq -r '.data[0].public_id // empty')

if [[ -z "$CHATBOT_ID" ]]; then
  echo "==> Creating load-test chatbot"
  CREATE=$(curl -sf -X POST "$API/chatbots" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d '{"name":"Load Test Bot","language":"en"}')
  CHATBOT_ID=$(echo "$CREATE" | jq -r '.data.id')
  CHATBOT_PUBLIC_ID=$(echo "$CREATE" | jq -r '.data.public_id')

  # Activate it
  curl -sf -X PATCH "$API/chatbots/$CHATBOT_ID" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d '{"status":"active"}' > /dev/null
fi

echo "Chatbot UUID:      $CHATBOT_ID"
echo "Chatbot Public ID: $CHATBOT_PUBLIC_ID"

# ── 3. Upload sample document (for vector search tests) ──────────────────────
echo "==> Uploading sample document for vector search"

# Generate a minimal valid PDF (text/plain fallback if ghostscript unavailable)
FIXTURE_PDF="load-tests/fixtures/sample.pdf"

if [[ ! -f "$FIXTURE_PDF" ]]; then
  echo "   Generating sample.pdf..."
  mkdir -p load-tests/fixtures

  if command -v gs &>/dev/null; then
    # Generate a real PDF using Ghostscript
    gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile="$FIXTURE_PDF" \
      -c "[/Title (Load Test Document)] setpagedevice" \
      -c "1 1 moveto (This is a load test document for ReplyIQ performance testing.) show showpage"
  else
    # Minimal valid PDF (base64-encoded 1-page PDF)
    echo "JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2Jq\
CjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2Jq\
CjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIg\
NzkyXSAvQ29udGVudHMgNCAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCA0NCA+Pgpz\
dHJlYW0KQlQKL0YxIDEyIFRmCjcyIDcyMCBUZAooTG9hZCBUZXN0IERvY3VtZW50KSBUagpFVApl\
bmRzdHJlYW0KZW5kb2JqCnhyZWYKMCA1CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAw\
MDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4gCjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDIx\
NiAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDUgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjMx\
MAolJUVPRgo=" | base64 -d > "$FIXTURE_PDF"
  fi
  echo "   Created $FIXTURE_PDF"
else
  echo "   Using existing $FIXTURE_PDF"
fi

DOC_UPLOAD=$(curl -sf -X POST "$API/chatbots/$CHATBOT_ID/documents" \
  -H "Authorization: Bearer $TOKEN" \
  -F "file=@$FIXTURE_PDF;type=application/pdf" \
  -F "title=Load Test Document")

echo "Document uploaded: $(echo "$DOC_UPLOAD" | jq -r '.data.id')"

# ── 4. Write env file for k6 ─────────────────────────────────────────────────
ENV_FILE="load-tests/.env.k6"
cat > "$ENV_FILE" << EOF
# Generated by setup.sh — source this before running k6
export API_BASE_URL=$API
export CHATBOT_PUBLIC_ID=$CHATBOT_PUBLIC_ID
export CHATBOT_UUID=$CHATBOT_ID
export DASHBOARD_TOKEN=$TOKEN
EOF

echo ""
echo "==> Done. Environment written to $ENV_FILE"
echo ""
echo "To run load tests:"
echo "   source $ENV_FILE"
echo "   k6 run load-tests/scenarios/widget-chat.js"
echo "   k6 run load-tests/scenarios/document-ingestion.js"
echo "   k6 run load-tests/scenarios/dashboard-browse.js"
echo "   k6 run load-tests/scenarios/vector-search.js"
